---
# This playbook contains plays to clone all C2 frameworks included in the C2 Matrix
# URL: https://howto.thec2matrix.com/

- name: Creating C2 directory in "{{ base_dir+c2_dir }}"
  file:
    path: "{{ base_dir+c2_dir }}"
    state: directory
    mode: '0755'

- name: cloning c2 frameworks
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+c2_dir }}{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/its-a-feature/apfell
    - https://github.com/mitre/caldera
    - https://github.com/cobbr/covenant
    - https://github.com/bc-security/empire.git
    - https://github.com/elevenpaths/ibombshell.git
    - https://github.com/zerosum0x0/koadic
    - https://github.com/ne0nd0g/merlin
    - https://github.com/p3nt4/nuages.git
    - https://github.com/adrianvollmer/powerhub.git
    - https://github.com/byt3bl33d3r/silenttrinity
    - https://github.com/bishopfox/sliver
    - https://github.com/trustedsec/trevorc2.git
    - https://github.com/nettitude/poshc2

- name: cloning c2 frameworks
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+c2_dir }}{{ item.split('/')[-1].replace('.git','')}}"
    version: main
  loop:
    - https://github.com/factionc2/faction
