---
# This playbook contains plays to grab RE frameworks/packages

- name: Creating RE directory in {{ base_dir+re_dir }}
  file:
    path: "{{ base_dir+re_dir }}"
    state: directory
    mode: '0755'

# IDA version list: https://www.hex-rays.com/products/ida/support/download_freeware/
- name: "Downloading RE Frameworks (IDA & Ghidra & Cutter)"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ base_dir+re_dir }}"
    mode: '0755'
      #checksum: "{{ item.checksum }}"
  loop:
    - { url: "https://out7.hex-rays.com/files/idafree70_linux.run", checksum: 'sha256:136e0e1995f16e1ff85244c269450fa91fb5454a565ca7623712f34ac004e245'}
    - { url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.2_build/ghidra_10.2.2_PUBLIC_20221115.zip", checksum: 'sha256:feb8a795696b406ad075e2c554c80c7ee7dd55f0952458f694ea1a918aa20ee3'}
    - { url: "https://github.com/rizinorg/cutter/releases/download/v2.1.2/Cutter-v2.1.2-Linux-x86_64.AppImage", checksum: 'sha256:bae4420ecd2ee399e5b2da0a8f6ba92768b0fb575864aed879f2439043efda08'}

- name: Running IDA Installer
  command: "{{ base_dir+re_dir }}idafree70_linux.run --mode unattended --prefix {{ base_dir+re_dir }}idafree --installpassword \"\" "

- name: Unzipping Ghidra
  raw: "cd {{ base_dir+re_dir }} && unzip -n ghidra*.zip"

- name: Installing Python bindings for capstone/unicorn/keystone/ropper/pwntools
  pip:
    name: "{{ item }}"
  loop:
    - capstone 
    - unicorn
    - keystone-engine
    - ropper
    - pwntools

- name: Downloading GEF (GDB Enhanced Features) from GitHub
  get_url: 
    url: https://raw.githubusercontent.com/hugsy/gef/main/scripts/gef.sh 
    dest: /tmp/gef.sh

- name: Installing GEF from /tmp/gef.sh.
  script: 
    cmd: /tmp/gef.sh

