---
- name: Creating Network directory in "{{ base_dir+network_dir }}"
  file:
    path: "{{ base_dir+network_dir }}"
    state: directory
    mode: '0755'

- name: Cloning Network tools 
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+network_dir }}"
    version: master
  loop:
    - https://github.com/SecureAuthCorp/impacket.git
    - https://github.com/pentestmonkey/smtp-user-enum.git
    - https://github.com/pentestmonkey/ftp-user-enum.git
    - https://github.com/pentestmonkey/finger-user-enum.git
    - https://github.com/pentestmonkey/rsh-grind.git
