---
- name: Creating Linux Pwn directory in "{{ base_dir+pwn_lin_dir }}"
  file:
    path: "{{ base_dir+pwn_lin_dir }}"
    state: directory
    mode: '0755'

- name: Cloning Linux Focused tools  - Enumeration
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+pwn_lin_dir }}/enumeration/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
    - https://github.com/rebootuser/LinEnum
    - https://github.com/diego-treitos/linux-smart-enumeration

- name: Cloning Linux Focused tools  - Payload Crafting
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+pwn_lin_dir }}/payload_crafting/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/gaffe23/linux-inject
    - https://github.com/gianlucaborello/libprocesshider

- name: Cloning Linux Focused tools  - Web
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+pwn_lin_dir }}/web/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/OJ/gobuster
    - https://github.com/tls-attacker/TLS-Attacker

- name: Cloning Linux Focused tools  - Cred Dumping
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+pwn_lin_dir }}/cred_dumping/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/huntergregal/mimipenguin
    - https://github.com/AlessandroZ/LaZagne

- name: Cloning Linux Focused tools  - rootkits
  git:
    repo: "{{ item }}"
    dest: "{{ base_dir+pwn_lin_dir }}/rootkits/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/f0rb1dd3n/Reptile
    - https://github.com/mempodippy/vlany
    - https://github.com/chokepoint/azazel
    - https://github.com/chokepoint/Jynx2
    - https://github.com/chokepoint/jynxkit
    - https://github.com/ChristianPapathanasiou/apache-rootkit
    - https://github.com/mncoppola/suterusu
    - https://github.com/jermeyyy/rooty
    - https://github.com/m0nad/Diamorphine

